Almost full rrr compose network generation working

diff --git a/tusk.yml b/tusk.yml
--- a/tusk.yml
+++ b/tusk.yml
@@ -1,73 +1,164 @@
 interpreter: bash -c
 name: blockbench
 options:
-  configdir:
+
+  launchdir:
+    # treat this as private
     usage: >
-      The common root for the config. Defaults to the launch directory. All
-      options are relative to this directory.
+      Don't set this option. Its a work around for a go-tusk peculiarity
     environment: PWD
+
   config:
     usage: >
       Base filename of the config file to use in configdir. Enables alternate
       configs for the same network.
     default:
       bench.json
+  configshow:
+    usage: "Report which, if any, supported configdir config file VAR's"
+    type: bool
 
   gethimage:
     usage: >
       Image name to use for geth. (prioritised over bench.json)
 
-  env:
-    private: true
-    usage: >
-      This option exists to force reading of the config early and once. It can
-      not be set on the command line
-    default:
-      command: |
-        echo $(cd ${configdir} && \
-        python3 -c \
-        "import json; [print(f'export {k}=\"{v}\"') for k, v in json.load(open('${config}')).items()]")
+  # private vars
   thistusk:
     private: true
     usage: "so this tusk file can refer to its own file name for recursive execution"
-    default: tusk.yml
+    default:
+      command: echo $(pwd)/tusk.yml
 
   configvars:
     private: true
     usage: >
       The list of config VARS supported by most tasks. Use --configshow
       for any command to get the definite list.
-    default: "nodesdir maxnodes image genesis quorum_src pyenv"
-  configshow:
-    usage: "Report which, if any, supported configdir config file VAR's"
-    type: bool
+    default: "nodesdir maxnodes image genesis quorum_src geth_image delve_image pyenv"
 
 tasks:
 
-  gendoc:
+  rrrcfg-compose:
+    usage: >
+      Configure a new docker compose based rrr network
+      # This task also ilustrates the full sequence of steps to prepare an rrr
+      # compose setup
+    options:
+      maxnodes:
+        default: 17
+
+      geth_image:
+        usage: "the docker image to use for geth-rrr"
+        default: "eu.gcr.io/fetlar-1/geth-rrr:fetlar-latest"
+      delve_image:
+        usage: "the docker image to use for running geth-rrr in for remote debug"
+        default: "eu.gcr.io/fetlar-1/rrr-delve:fetlar-latest"
+
+      quorum_src:
+        usage: |
+            the host directory to be mounted as /go/src/quorum. must contain quorum clone.
+            only required if you need to interactively debug the node.
+        default:
+          command: echo "${launchdir}/quorum"
+      rrr_src:
+        default:
+          command: echo "${launchdir}/go-rrr"
+
+      maxnodes:
+        usage: "the total number of nodes for the network"
+        default: 17
+
+    args:
+      configdir:
+        usage: Directory to put the network in
+    run:
+      - task:
+          name: configure
+          args:
+            - ${configdir}
+      - task:
+          name: rrrinit
+          options:
+            geth_image: ${geth_image}
+            delve_image: ${delve_image}
+            maxnodes: ${maxnodes}
+            quorum_src: ${quorum_src}
+            rrr_src: ${rrr_src}
+          args:
+            - ${configdir}
+      - task:
+          name: gethkeys
+          args:
+            - ${configdir}
+      - task:
+          name: rrralpha
+          args:
+            - ${configdir}
+      - task:
+          name: rrrgen
+          args:
+            - ${configdir}
+      - task:
+          name: rrrcompose
+          args:
+            - ${configdir}
+
+  configure:
+    usage: >
+      Put the rune for reading the config file into an environment variable so
+      that it can be more readily re-used.  This one horror pays for a lot of
+      simplicity elsewhere. The double cd trick combines the launchdir captured
+      before tusk changes directory to the task file and then combines it with
+      the cli choice of current directory. So that the cli choice remains
+      relative to the launchdir.  Then we suck out the top level fields in the
+      json config directory and expose them in a bash friendly format. This
+      enables both shell tusk tasks and python to share the same config,
+      without having to duplicate a bunch of stuff.
+    private: true
+    args:
+      configdir:
+    run:
+      # execute these fragments in the task like this:
+      #   CONFIGVARS="${configvars} extra_config_var1 extra_config_var2"
+      #   eval ${READ_CONFIG}
+      #   if ${configshow}; then eval ${SHOW_CONFIG}; exit 0; fi
+      set-environment: {
+        READ_CONFIG: "\
+          $(cd ${launchdir} && cd ${configdir} \
+          && python3 -c \"import json; \
+                          [print(f'export {k}=\"{v}\"') \
+                              for k, v in json.load(open('${config}')).items()]\")",
+        SHOW_CONFIG: "for v in ${CONFIGVARS}; do echo $v=${!v}; done"}
+
+  gethgendoc:
     usage: render the template gensis document refered to by the configuration
     options:
-      account:
-        usage: "the wallet to allocate the genesis balance to - suggest you change the default!"
-        short: "w"
-        default: "0x5b38ab0d3a31efeffd3a3ac88421816ca227432c"
       extra:
         usage: "extraData for the genesis doc"
         default: ""
+    args:
+      configdir:
+        usage: >
+          The config root directory.
+
     run:
+      - task:
+          name: configure
+          args:
+            - ${configdir}
       - command:
           exec: |
             set -e
-
-            cd ${configdir}
-
             CONFIGVARS="${configvars} gendoc_extra gendoc_wallet gendoc_balance"
-            eval $(echo -e "${env}")
-            if ${configshow}; then
-              for v in ${CONFIGVARS}; do echo "$v=${!v}"; done
-              exit 0
-            fi
-            [ -n "${extra}" ] && gendoc_extra="${extra}"
+            eval ${READ_CONFIG}
+            if ${configshow}; then eval ${SHOW_CONFIG}; exit 0; fi
+            cd ${launchdir} && cd ${configdir}
+
+            EXTRADATA=""
+            [ -n "${gendoc_extra}" ] && EXTRADATA="${gendoc_extra}"
+            [ -n "${extra}" ] && EXTRADATA="${extra}"
+            export EXTRADATA
+
             cat <<PYEND | python3
             import os, json
             from pathlib import Path
@@ -79,38 +170,50 @@ tasks:
                 del o["alloc"]["0x0000000000000000000000000000000000000000"]
             except KeyError:
                 pass
-            o["alloc"]["${account}"] = dict(balance="${gendoc_balance}")
+            o["alloc"][os.environ["gendoc_wallet"]] = dict(balance="${gendoc_balance}")
 
-            extraData = os.environ["gendoc_extra"]
+            extraData = os.environ["EXTRADATA"]
             if not extraData.startswith("0x"):
                 extraData = "0x" + extraData
             o["extraData"] = extraData
             print(json.dumps(o, indent=2, sort_keys=True))
             PYEND
 
-  genkeys:
+  gethkeys:
     usage: "regenerate all node keys and wallets"
+    args:
+      configdir:
+        usage: >
+          The config root directory.
     run:
+      - task:
+          name: configure
+          args:
+            - ${configdir}
+
       - command:
           exec: |
             set -e
+            CONFIGVARS="${configvars} gendoc_extra gendoc_wallet gendoc_balance"
+            eval ${READ_CONFIG}
+            if ${configshow}; then eval ${SHOW_CONFIG}; exit 0; fi
+            cd ${launchdir} && cd ${configdir}
 
-            cd ${configdir}
+            source ${pyenv}/bin/activate
 
-            CONFIGVARS="${configvars}"
-            eval $(echo -e "${env}")
-            if ${configshow}; then
-              for v in ${CONFIGVARS}; do echo "$v=${!v}"; done
-              exit 0
-            fi
+            # Use the address of node0's node key as the genesis account (which
+            # gets the gendoc_balance)
             source ${pyenv}/bin/activate
 
             cat <<PYEND | python3
-            import os, coincurve
+            import os, json, coincurve
             from pathlib import Path
 
             for i in range(int(os.environ['maxnodes'])):
+
                 dirname = f"{os.environ['nodesdir']}/node{i}"
+
+                Path(dirname).mkdir(parents=True, exist_ok=True)
 
                 # delete the keys first so we don't ever end up in a weird state
                 for fn in ("key", "enode"):
@@ -127,44 +230,283 @@ tasks:
                     with open(Path(f"{dirname}/{fn}"), "w") as f:
                         f.write(locals()[fn])
                         print(f"Wrote {dirname}/{fn}")
-            PYEND
 
-  # rrr consensus
-  rrrgen:
-    usage: "recreate the genesis document (without changing keys or alpha)"
+            # Now make node0 the genesis wallet
+            keyfile = f"{os.environ['nodesdir']}/node0/key"
+            pub = None
+            with open(Path(keyfile)) as f:
+                pub = coincurve.PrivateKey.from_hex(f.read()).public_key.format(compressed=False)[1:]
+            addr = pub[-20:]
+
+            j = None
+            with open("bench.json") as f:
+                j = json.load(f)
+            j["gendoc_wallet"] = addr.hex()
+            j["bootnode0"] = pub.hex()
+            with open("bench.json", "w") as f:
+                json.dump(j, f, indent=2, sort_keys=True)
+            PYEND
+            echo "gethkeys: done"
+            cat bench.json
+            echo "updated gendoc_wallet: done"
+
+
+            cat <<END > bootnodes.env
+            BOOTNODE0_PUB=$(cat ${nodesdir}/node0/enode)
+            END
+            cat bootnodes.env
+            echo "Updated bootnode.env for docker-compose"
+
+            if [ -f env.env ]; then
+              cat env.env bootnodes.env > .env
+              cat .env
+              echo "Updated .env for docker-compose"
+            fi
+
+  # rrr consensus commands
+  # rrr - init
+  rrrinit:
+    usage: "inititialise for rrr consensus network"
+    args:
+      configdir:
+        usage: >
+          The config root directory.
     options:
-      account:
-        usage: "the wallet to allocate the genesis balance to - suggest you change the default!"
-        short: "w"
-        default: "0x5b38ab0d3a31efeffd3a3ac88421816ca227432c"
+      nodesdir:
+        usage: "relative to configdir. each node gets a subdirectory here named node{N}"
+        default: nodes
+      maxnodes:
+        usage: "the total number of nodes for the network"
+        default: 17
+      genesis:
+        default: "genesis-in.json"
+      gendoc_balance:
+        default: "1000000000000000000000000000"
+      geth_image:
+        usage: "the docker image to use for geth-rrr"
+        default: "eu.gcr.io/fetlar-1/geth-rrr:fetlar-latest"
+      delve_image:
+        usage: "the docker image to use for running geth-rrr in for remote debug"
+        default: "eu.gcr.io/fetlar-1/rrr-delve:fetlar-latest"
+      quorum_src:
+        usage: |
+            the host directory to be mounted as /go/src/quorum. must contain quorum clone.
+            only required if you need to interactively debug the node.
+        # TODO: adjust the compose file so this can be ../../quorum
+        default:
+          command: echo "${launchdir}/quorum"
+      rrr_src:
+        default:
+          command: echo "${launchdir}/go-rrr"
+
     run:
       - command:
           exec: |
             set -e
-            EXTRADATA=$(tusk -qf ${thistusk} rrrextra --configdir=${configdir})
-            tusk -qf ${thistusk} gendoc --extra $EXTRADATA --configdir=${configdir} --account ${account}
+
+            TUSKDIR=$(pwd)
+
+            cd ${launchdir} && mkdir -p ${configdir} && cd ${configdir}
+            mkdir -p ${nodesdir}/node0
+
+
+            # we don't allow this to be set on the cli, if you want another
+            # env thats fine, just edit bench.json afterwords to point to yours
+            # and make sure you install the requirements.txt
+            pyenv="env"
+
+            echo "Initialising in: $(pwd)"
+
+            python3 -m venv ${pyenv}
+            source ${pyenv}/bin/activate
+            pip3 install -r ${TUSKDIR}/requirements.txt
+
+            # generate the config from the options
+            cat <<JEND  > bench.json
+            {
+              "pyenv": "${pyenv}",
+              "maxnodes": "${maxnodes}",
+              "nodesdir": "$(pwd)/${nodesdir}",
+              "quorum_src": "${quorum_src}",
+              "geth_image": "${geth_image}",
+              "delve_image": "${delve_image}",
+              "rrr_src": "${rrr_src}",
+              "genesis": "${genesis}",
+              "gendoc_balance": "${gendoc_balance}"
+            }
+            JEND
+
+            cat bench.json
+            echo "Wrote: $(pwd)/bench.json"
+
+
+  # rrr - genesis
+  rrrgen:
+    usage: "rrr genesis - keeps existing keys and alpha contributions"
+    options:
+      sudo:
+        type: bool
+    args:
+      configdir:
+        usage: >
+          The config root directory.
+    run:
+      - task:
+          name: configure
+          args:
+            - ${configdir}
+      - command:
+          exec: |
+            set -e
+
+            TUSKDIR=$(pwd)
+
+            CONFIGVARS="${configvars}"
+            eval ${READ_CONFIG}
+            if ${configshow}; then eval ${SHOW_CONFIG}; exit 0; fi
+            cd ${launchdir} && cd ${configdir}
+
+            CONFIGDIR=$(pwd)
+
+            cp ${TUSKDIR}/compose/rrr/genesis-in.json .
+
+            pushd ${launchdir} # restore launchdir before recursive invoke
+
+              EXTRADATA=$(tusk -qf ${thistusk} rrrextra ${configdir})
+              tusk -qf ${thistusk} gethgendoc ${configdir} --extra $EXTRADATA | tee ${CONFIGDIR}/genesis.json
+
+            popd
+
+            # clear out all the data dirs first to avoid mixed state if we fail
+            # half way through
+            ${sudo} && dosudo="sudo" || dosudo=""
+            set -x
+            for i in $(seq 0 ${maxnodes}); do
+              ${dosudo} rm -rf ${nodesdir}/node$i/data
+            done
+
+            for i in $(seq 0 ${maxnodes}); do
+              rm -rf ${nodesdir}/node$i/data
+            done
+
+            genesis_doc=$(pwd)/genesis.json
+            for i in $(seq 0 ${maxnodes}); do
+              geth="docker run --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) ${geth_image} --nousb"
+              ${geth} --datadir=$(pwd)/nodes/node${i}/data init $(pwd)/genesis.json
+            done
+
+
+
+  # rrr support commands
+  rrrcompose:
+    usage: |
+      Generate a docker compose configuration for running rrr
+    options:
+      compose_project:
+        default: "rrr"
+      networkid:
+        default: "53456"
+      netrestrict:
+        default: 172.19.0.10/24
+    args:
+      configdir:
+        usage: >
+          The config root directory.
+
+    run:
+      - task:
+          name: configure
+          args:
+            - ${configdir}
+      - command:
+          exec: |
+            set -e
+
+            TUSKDIR=$(pwd)
+
+            CONFIGVARS="${configvars} rrr_src gendoc_extra gendoc_wallet gendoc_balance"
+            eval ${READ_CONFIG}
+            if ${configshow}; then eval ${SHOW_CONFIG}; exit 0; fi
+
+            cd ${launchdir} && cd ${configdir}
+
+            cp ${TUSKDIR}/compose/rrr/base.yml .
+            cp ${TUSKDIR}/compose/rrr/node.yml .
+            cp base.yml docker-compose.yml
+
+
+            cat <<END > env.env
+            COMPOSE_PROJECT_NAME=${compose_project}
+            NETWORKID=${networkid}
+            NETRESTRICT=${netrestrict}
+            ETHERBASE=${gendoc_wallet}
+            QUORUM_SRC=${quorum_src}
+            RRR_SRC=${rrr_src}
+            NODESDIR=${nodesdir}
+            GETH_IMAGE= ${geth_image}
+            DELVE_IMAGE=${delve_image}
+            END
+            cat env.env
+            echo "Wrote env.env"
+
+            cat <<END > bootnodes.env
+            BOOTNODE0_PUB=$(cat ${nodesdir}/node0/enode)
+            END
+
+            cat bootnodes.env
+            echo "Wrote bootnodes.env"
+
+            cat env.env bootnodes.env > .env
+            cat .env
+            echo "Wrote .env"
+
+            # Merge in the appropriate number of copies of node.yml to the
+            # docker-compose.yml we are generating.
+
+            # each document fragment has to be valid. so they all need the
+            # x-node-defaults anchor to be defined.
+            cat <<END > tmp.yml
+            x-node-defaults:
+              &node-defaults
+            END
+            for i in $(seq 0 $((${maxnodes} - 1)))
+            do
+                VAL=$i yq eval '
+                  .node |= .working_dir += env(VAL) | del(.x-node-defaults) |
+                  with_entries(.key |= .  + env(VAL))
+                ' node.yml
+            done >> tmp.yml
+            yq eval-all --inplace '
+                select(fileIndex == 0) * {"services": select(fileIndex == 1)}
+                | del(.services.x-node-defaults)' docker-compose.yml tmp.yml
+            # yq eval-all --inplace 'select(fileIndex == 0) * {"services": select(fileIndex == 1)} | del(.services.x-node-defaults)' docker-compose.yml tmp.yml
 
   rrralpha:
     usage: "generate the rrr alpha.json docs required by rrrextra (for the genesis VRF seed)"
+    args:
+      configdir:
+        usage: >
+          The config root directory.
     run:
+      - task:
+          name: configure
+          args:
+            - ${configdir}
+
       - command:
           exec: |
             set -e
+            CONFIGVARS="${configvars} gendoc_extra gendoc_wallet gendoc_balance"
+            eval ${READ_CONFIG}
+            if ${configshow}; then eval ${SHOW_CONFIG}; exit 0; fi
+            cd ${launchdir} && cd ${configdir}
 
-            cd ${configdir}
-
-            CONFIGVARS="${configvars}"
-            eval $(echo -e "${env}")
-            if ${configshow}; then
-              for v in ${CONFIGVARS}; do echo "$v=${!v}"; done
-              exit 0
-            fi
             source ${pyenv}/bin/activate
-
             cat <<PYEND | python3
             import os, coincurve, sha3, secrets, pathlib
 
             for i in range(int(os.environ['maxnodes'])):
+
                 dirname = f"{os.environ['nodesdir']}/node{i}"
 
                 key = open(f"{dirname}/key", 'r').read()
@@ -188,19 +530,24 @@ tasks:
       showids:
         short: "i"
         type: bool
+
+    args:
+      configdir:
+        usage: >
+          The config root directory.
     run:
+      - task:
+          name: configure
+          args:
+            - ${configdir}
+
       - command:
           exec: |
             set -e
-
-            cd ${configdir}
-
-            CONFIGVARS="${configvars} rrr_src"
-            eval $(echo -e "${env}")
-            if ${configshow}; then
-              for v in ${CONFIGVARS}; do echo "$v=${!v}"; done
-              exit 0
-            fi
+            CONFIGVARS="${configvars} gendoc_extra gendoc_wallet gendoc_balance"
+            eval ${READ_CONFIG}
+            if ${configshow}; then eval ${SHOW_CONFIG}; exit 0; fi
+            cd ${launchdir} && cd ${configdir}
 
             # we cd to run the rrr tool, so these need to be absoloute
             nodesdir=$(cd ${nodesdir} && pwd)
