wip workflows

diff --git a/.github/workflows/loadtest-on-gcp.yaml b/.github/workflows/loadtest-on-gcp.yaml
--- a/.github/workflows/loadtest-on-gcp.yaml
+++ b/.github/workflows/loadtest-on-gcp.yaml
@@ -121,6 +121,8 @@ jobs:
         name: generate transaction load
         run: |
 
+          echo "force fail" && exit 1
+
           ATTEMPTS_REMAINING=100
           NAME=${{ inputs.consensus }}${{ inputs.numnodes }}
           NAMESPACE=github-$NAME
